//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.18444
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Clover.Core.Properties {
    using System;
    
    
    /// <summary>
    ///   一个强类型的资源类，用于查找本地化的字符串等。
    /// </summary>
    // 此类是由 StronglyTypedResourceBuilder
    // 类通过类似于 ResGen 或 Visual Studio 的工具自动生成的。
    // 若要添加或移除成员，请编辑 .ResX 文件，然后重新运行 ResGen
    // (以 /str 作为命令选项)，或重新生成 VS 项目。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class RegexResource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal RegexResource() {
        }
        
        /// <summary>
        ///   返回此类使用的缓存的 ResourceManager 实例。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Clover.Core.Properties.RegexResource", typeof(RegexResource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   使用此强类型资源类，为所有资源查找
        ///   重写当前线程的 CurrentUICulture 属性。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   查找类似 ^[a-zA-Z][a-zA-Z0-9_]{4,15}$ 的本地化字符串。
        /// </summary>
        internal static string RegxForAccount {
            get {
                return ResourceManager.GetString("RegxForAccount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 [\u4e00-\u9fa5] 的本地化字符串。
        /// </summary>
        internal static string RegxForChinese {
            get {
                return ResourceManager.GetString("RegxForChinese", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 \d{15}|\d{18} 的本地化字符串。
        /// </summary>
        internal static string RegxForChZnIdNumber {
            get {
                return ResourceManager.GetString("RegxForChZnIdNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 [^\x00-\xff] 的本地化字符串。
        /// </summary>
        internal static string RegxForDoubleCode {
            get {
                return ResourceManager.GetString("RegxForDoubleCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 \w+([-+.&apos;]\w+)*@\w+([-.]\w+)*\.\w+([-.]\w+)* 的本地化字符串。
        /// </summary>
        internal static string RegxForEmail {
            get {
                return ResourceManager.GetString("RegxForEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 ^(-([1-9]\d*\.\d*|0\.\d*[1-9]\d*))|0?\.0+|0$ 的本地化字符串。
        /// </summary>
        internal static string RegxForFloat {
            get {
                return ResourceManager.GetString("RegxForFloat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 &lt;(\S*?)[^&gt;]*&gt;.*?&lt;/\1&gt;|&lt;.*? /&gt; 的本地化字符串。
        /// </summary>
        internal static string RegxForHtmlCode {
            get {
                return ResourceManager.GetString("RegxForHtmlCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 ^((2[0-4]\d|25[0-5]|[01]?\d\d?)\.){3}(2[0-4]\d|25[0-5]|[01]?\d\d?)$ 的本地化字符串。
        /// </summary>
        internal static string RegxForIP {
            get {
                return ResourceManager.GetString("RegxForIP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 \d{3}-\d{8}|\d{4}-\d{7} 的本地化字符串。
        /// </summary>
        internal static string RegxForPhone {
            get {
                return ResourceManager.GetString("RegxForPhone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 \n\s*\r 的本地化字符串。
        /// </summary>
        internal static string RegxForSpace {
            get {
                return ResourceManager.GetString("RegxForSpace", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 ^([a-zA-Z]:)(\\([-_a-zA-Z0-9\u4e00-\u9fa5][-_a-zA-Z0-9\u4e00-\u9fa5].*))(.jpg|.JPG|.gif|.GIF|.doc|.xls|.txt|.pdf|.GD|.rar|.png|.doc|.xls|.ppt)$ 的本地化字符串。
        /// </summary>
        internal static string RegxForUploadFilePath {
            get {
                return ResourceManager.GetString("RegxForUploadFilePath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 http(s)?://([\w-]+\.)+[\w-]+(/[\w- ./?%&amp;=]*)? 的本地化字符串。
        /// </summary>
        internal static string RegxForUrl {
            get {
                return ResourceManager.GetString("RegxForUrl", resourceCulture);
            }
        }
    }
}
