//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:2.0.50727.4952
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Clover.Core.Properties {
    using System;
    
    
    /// <summary>
    ///   强类型资源类，用于查找本地化字符串等。
    /// </summary>
    // 此类是由 StronglyTypedResourceBuilder
    // 类通过类似于 ResGen 或 Visual Studio 的工具自动生成的。
    // 若要添加或移除成员，请编辑 .ResX 文件，然后重新运行 ResGen
    // (以 /str 作为命令选项)，或重新生成 VS 项目。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "2.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   返回此类使用的缓存 ResourceManager 实例。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Clover.Core.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   为使用此强类型资源类的所有资源查找
        ///   重写当前线程的 CurrentUICulture 属性。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   查找类似 You passed a file-name-only (&apos;{ConnectionString}&apos;) as the connection string to CompactJetDatabase(). Please use the FileInfo-overload instead. 的本地化字符串。
        /// </summary>
        public static string Str_AdoNetOleDBHelper_CompactJetDatabase_Error01 {
            get {
                return ResourceManager.GetString("Str_AdoNetOleDBHelper_CompactJetDatabase_Error01", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 The specified source file path &apos;{SourceFilePath}&apos; path does not exists. 的本地化字符串。
        /// </summary>
        public static string Str_AdoNetOleDBHelper_CompactJetDatabase_Error02 {
            get {
                return ResourceManager.GetString("Str_AdoNetOleDBHelper_CompactJetDatabase_Error02", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 You passed a file-name-only (&apos;{ConnectionString}&apos;) as the connection string to RefreshJetCache(). Please use the FileInfo-overload instead! 的本地化字符串。
        /// </summary>
        public static string Str_AdoNetOleDBHelper_CompactJetDatabase_Error03 {
            get {
                return ResourceManager.GetString("Str_AdoNetOleDBHelper_CompactJetDatabase_Error03", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 A maximum of one default task may be specified, but there are {Count} default tasks specified. 的本地化字符串。
        /// </summary>
        public static string Str_Clover_Core_Base_Tasks_TaskBase_DispatchTasks_01 {
            get {
                return ResourceManager.GetString("Str_Clover_Core_Base_Tasks_TaskBase_DispatchTasks_01", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 无效的参数 的本地化字符串。
        /// </summary>
        public static string Str_Clover_Core_Caching_CacheItemInformation_01 {
            get {
                return ResourceManager.GetString("Str_Clover_Core_Caching_CacheItemInformation_01", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 The LDAP server was not specified. 的本地化字符串。
        /// </summary>
        public static string Str_Clover_Core_Common_ActiveDirectory_01 {
            get {
                return ResourceManager.GetString("Str_Clover_Core_Common_ActiveDirectory_01", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 User with GUID &apos;{Guid}&apos; not found in Active Directory. 的本地化字符串。
        /// </summary>
        public static string Str_Clover_Core_Common_ActiveDirectory_02 {
            get {
                return ResourceManager.GetString("Str_Clover_Core_Common_ActiveDirectory_02", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 A name must be provided and cannot be null. 的本地化字符串。
        /// </summary>
        public static string Str_Clover_Core_Common_Dump_01 {
            get {
                return ResourceManager.GetString("Str_Clover_Core_Common_Dump_01", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 A name must be provided and cannot be empty. 的本地化字符串。
        /// </summary>
        public static string Str_Clover_Core_Common_Dump_02 {
            get {
                return ResourceManager.GetString("Str_Clover_Core_Common_Dump_02", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 The file extension must be specified. 的本地化字符串。
        /// </summary>
        public static string Str_Clover_Core_Common_Misc_FileExtensionRegistration_01 {
            get {
                return ResourceManager.GetString("Str_Clover_Core_Common_Misc_FileExtensionRegistration_01", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 info.ClassName must be non-empty. 的本地化字符串。
        /// </summary>
        public static string Str_Clover_Core_Common_Misc_FileExtensionRegistration_02 {
            get {
                return ResourceManager.GetString("Str_Clover_Core_Common_Misc_FileExtensionRegistration_02", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 info.Description must be non-empty. 的本地化字符串。
        /// </summary>
        public static string Str_Clover_Core_Common_Misc_FileExtensionRegistration_03 {
            get {
                return ResourceManager.GetString("Str_Clover_Core_Common_Misc_FileExtensionRegistration_03", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 info.ApplicationFilePath must be non-empty. 的本地化字符串。
        /// </summary>
        public static string Str_Clover_Core_Common_Misc_FileExtensionRegistration_04 {
            get {
                return ResourceManager.GetString("Str_Clover_Core_Common_Misc_FileExtensionRegistration_04", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 The application registry key was not set. 的本地化字符串。
        /// </summary>
        public static string Str_Clover_Core_Common_Storage_01 {
            get {
                return ResourceManager.GetString("Str_Clover_Core_Common_Storage_01", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 参数值必须为类型 P. 的本地化字符串。
        /// </summary>
        public static string Str_Clover_Core_Data_AdoNetBaseHelper_01 {
            get {
                return ResourceManager.GetString("Str_Clover_Core_Data_AdoNetBaseHelper_01", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Unknown Database type: &apos;{Type}&apos;. 的本地化字符串。
        /// </summary>
        public static string Str_Clover_Core_Data_AdoNetOdbcHelper_01 {
            get {
                return ResourceManager.GetString("Str_Clover_Core_Data_AdoNetOdbcHelper_01", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Unknown Database type: &apos;{Type}&apos;. 的本地化字符串。
        /// </summary>
        public static string Str_Clover_Core_Data_AdoNetOleDBHelper_01 {
            get {
                return ResourceManager.GetString("Str_Clover_Core_Data_AdoNetOleDBHelper_01", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 The file or directory of configuration is not exists. 的本地化字符串。
        /// </summary>
        public static string Str_Configuration_PathNotExists {
            get {
                return ResourceManager.GetString("Str_Configuration_PathNotExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Please specify a valid folder path for the deleted files! Currently &apos;{FolderPath}&apos; is specified. 的本地化字符串。
        /// </summary>
        public static string Str_FileDeleteHelper_Error01 {
            get {
                return ResourceManager.GetString("Str_FileDeleteHelper_Error01", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 bytes 的本地化字符串。
        /// </summary>
        public static string Str_FormatFileSize_Bytes {
            get {
                return ResourceManager.GetString("Str_FormatFileSize_Bytes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 GB 的本地化字符串。
        /// </summary>
        public static string Str_FormatFileSize_GB {
            get {
                return ResourceManager.GetString("Str_FormatFileSize_GB", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 kB 的本地化字符串。
        /// </summary>
        public static string Str_FormatFileSize_KB {
            get {
                return ResourceManager.GetString("Str_FormatFileSize_KB", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 MB 的本地化字符串。
        /// </summary>
        public static string Str_FormatFileSize_MB {
            get {
                return ResourceManager.GetString("Str_FormatFileSize_MB", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 TB 的本地化字符串。
        /// </summary>
        public static string Str_FormatFileSize_TB {
            get {
                return ResourceManager.GetString("Str_FormatFileSize_TB", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Logging could not be configured. Please ensure to call Clover.CoreLibraryConfiguration.Current.Initialize() once at the very start of your application, before doing any logging functions, if you are running a web application, a good place would be inside GLOBAL.ASAX. If you are running a Windows application, you usually do that right at the start of the MAIN function. 的本地化字符串。
        /// </summary>
        public static string Str_LogCentral_Error01 {
            get {
                return ResourceManager.GetString("Str_LogCentral_Error01", resourceCulture);
            }
        }
    }
}
